baseURL = "https:/salmanalibanani.netlify.app/"
languageCode = "en-us"
title = "Salman Ali Banani"
theme = "simple-blog"
copyright = "© 2020 copyright text."
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "<your site description>"

